#!/bin/bash

CONFIG_FILE=${1:-"local/wordpress.yaml"}
wraith save_latest_images -l '_new' $CONFIG_FILE
wraith compare_latest_images --label1 '_old' --label2='_new' $CONFIG_FILE
wraith latest_thumbnails $CONFIG_FILE
wraith latest_gallery $CONFIG_FILE

### Bring up both galleries up in forefox
echo " "
echo "All collected images are in: gallery_all.html"
echo "Only changed images are in:  gallery_diffs.html"
# firefox gallery_all.html
# firefox gallery_diffs.html
