##If you want to have multiple snapping files, set the file name here
snap_file: "snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domains:
  english: "http://thesassway.com"
  russian: "http://thesassway.com"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  #- 600
  #- 768
  #- 1024
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
   home: /
   beginner: /beginner

#Set the number of days to keep the site spider file
spider_days:
  - 10

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

